### ISSUE TITLE
Describe data in each folder on Google Cloud Storage bucket

### ISSUE THREAD

**Issue by CloudNiner** [cloudtostreet/Sen1Floods11#1]
Thanks for documenting this research here!

I'm reading through the paper, this github repo, and looking at the S3 bucket. When I list the GS bucket, I get:
```
gs://cnn_chips/CNN_Chips_FTC.geojson
gs://cnn_chips/Sen1Floods11_labeled.tgz
gs://cnn_chips/flood_bolivia_data.csv
gs://cnn_chips/flood_test_data.csv
gs://cnn_chips/flood_train_data.csv
gs://cnn_chips/flood_valid_data.csv
gs://cnn_chips/permanent_water_data.csv
gs://cnn_chips/permanent_water_test_data.csv
gs://cnn_chips/permanent_water_train_data.csv
gs://cnn_chips/permanent_water_validation_data.csv
gs://cnn_chips/NoQC/
gs://cnn_chips/Perm/
gs://cnn_chips/PermJRC/
gs://cnn_chips/QC_v2/
gs://cnn_chips/S1/
gs://cnn_chips/S1Flood/
gs://cnn_chips/S1Flood_NoQC/
gs://cnn_chips/S1Perm/
gs://cnn_chips/S1_NoQC/
gs://cnn_chips/S2/
gs://cnn_chips/S2Flood/
gs://cnn_chips/S2_NoQC/
gs://cnn_chips/cnn_checkpoints/
```

As part of the documentation in this repo, it would be helpful to have a brief (< 2 sentence) human readable description of what each of the directories and files in the bucket are for. For example, the only reference I can find to `S1Flood` is in the `getTradFName` function in `Test_Models.ipynb`. Does that mean that these are the labels for the `Otsu Threshold-VH` dataset or something else?

**Comment by tyler-c2s** [comment]
That sounds like a great idea, happy to implement that to improve ease of use

**Comment by CloudNiner** [comment]
🎉 thanks so much!
